CREATE VIEW Logging.LogInfo
AS
SELECT [TaskLog].[TaskId]
      ,[TaskLog].[TaskName]
      ,[TaskLog].[StartTime]                   as [TaskStartTime]
      ,[TaskLog].[EndTime]                     as [TaskEndTime]
      ,DATEDIFF(MILLISECOND, [TaskLog].[StartTime], [TaskLog].[EndTime]) as [TaskDuration]
      ,[TaskLog].[ExecutionParameters]         as [TaskExecutionParameters]
      ,[TaskLog].[Status]                      as [TaskStatus]
      ,[TaskLog].[ErrorDetails]                as [TaskErrorDetails]
      ,[TaskLog].[CreatedBy]                   as [TaskCreatedBy]
      ,[TaskLog].[CreatedAt]                   as [TaskCreatedAt]
	  ,[StepLog].[StepId]
      ,[StepLog].[StepName]
      ,[StepLog].[StartTime]                     as [StepStartTime]
      ,[StepLog].[EndTime]						as [StepEndTime]
      ,DATEDIFF(MILLISECOND, [StepLog].[StartTime], [StepLog].[EndTime]) as [StepDuration]
      ,[StepLog].[ExecutionParameters]			as [StepExecutionParameters]
      ,[StepLog].[Status]						as [StepStatus]
      ,[StepLog].[ErrorDetails]					as [StepErrorDetails]
      ,[StepLog].[CreatedBy]						as [StepCreatedBy]
      ,[StepLog].[CreatedAt]						as [StepCreatedAt]
  FROM [Logging].[TaskLog]
    LEFT OUTER JOIN  [Logging].[StepLog]
	  ON [TaskLog].[TaskId] = [StepLog].[TaskId]